-- ============================================================
-- Banco de testes (PostgreSQL)
-- ============================================================
DROP DATABASE IF EXISTS db_test_easy_talk;
CREATE DATABASE db_test_easy_talk;

-- A partir daqui, você precisa estar conectado em db_test_easy_talk.
-- Em psql:
\connect db_test_easy_talk;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;


-- ============================================================
-- Tabelas de suporte a permissões (stubs mínimas)
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_auth_group
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_auth_permission
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    codename VARCHAR(100) NOT NULL,
    CONSTRAINT tb_auth_permission_codename_uk UNIQUE (codename)
);


-- ============================================================
-- Usuario customizado
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_usuario
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password     VARCHAR(128) NOT NULL,
    last_login   TIMESTAMP(6) NULL,
    is_superuser BOOLEAN      NOT NULL DEFAULT FALSE,
    email        VARCHAR(254) NOT NULL,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    is_staff     BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT tb_usuario_email_uk UNIQUE (email)
);


-- ============================================================
-- ManyToMany: Usuario <-> Group
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_usuario_groups
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    group_id   INTEGER NOT NULL,
    CONSTRAINT tb_usuario_groups_usuario_group_uk UNIQUE (usuario_id, group_id),
    CONSTRAINT tb_usuario_groups_usuario_fk
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id)
            ON DELETE CASCADE,
    CONSTRAINT tb_usuario_groups_group_fk
        FOREIGN KEY (group_id)
            REFERENCES tb_auth_group (id)
            ON DELETE CASCADE
);


-- ============================================================
-- ManyToMany: Usuario <-> Permission
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_usuario_user_permissions
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    CONSTRAINT tb_usuario_user_permissions_usuario_perm_uk UNIQUE (usuario_id, permission_id),
    CONSTRAINT tb_usuario_user_permissions_usuario_fk
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id)
            ON DELETE CASCADE,
    CONSTRAINT tb_usuario_user_permissions_permission_fk
        FOREIGN KEY (permission_id)
            REFERENCES tb_auth_permission (id)
            ON DELETE CASCADE
);


-- ============================================================
-- Especializacao
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_especializacao
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo    VARCHAR(50) NOT NULL,
    descricao TEXT        NOT NULL,
    CONSTRAINT tb_especializacao_titulo_uk UNIQUE (titulo)
);


-- ============================================================
-- Paciente
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_paciente
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER      NOT NULL,
    nome       VARCHAR(50)  NOT NULL,
    cpf        VARCHAR(14)  NOT NULL,
    foto       VARCHAR(100) NULL,
    CONSTRAINT tb_paciente_cpf_uk    UNIQUE (cpf),
    CONSTRAINT tb_paciente_usuario_uk UNIQUE (usuario_id),
    CONSTRAINT tb_paciente_usuario_fk
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id)
            ON DELETE CASCADE
);


-- ============================================================
-- Psicologo
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_psicologo
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     INTEGER        NOT NULL,
    nome_completo  VARCHAR(50)    NOT NULL,
    crp            VARCHAR(20)    NOT NULL,
    foto           VARCHAR(100)   NULL,
    sobre_mim      TEXT           NULL,
    valor_consulta NUMERIC(10, 2) NULL CHECK (valor_consulta IS NULL OR valor_consulta >= 0),
    CONSTRAINT tb_psicologo_usuario_uk UNIQUE (usuario_id),
    CONSTRAINT tb_psicologo_crp_uk     UNIQUE (crp),
    CONSTRAINT tb_psicologo_usuario_fk
        FOREIGN KEY (usuario_id)
            REFERENCES tb_usuario (id)
            ON DELETE CASCADE
);


-- ============================================================
-- ManyToMany: Psicologo.especializacoes
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_psicologo_especializacoes
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    psicologo_id      INTEGER NOT NULL,
    especializacao_id INTEGER NOT NULL,
    CONSTRAINT tb_psicologo_especializacao_uk UNIQUE (psicologo_id, especializacao_id),
    CONSTRAINT tb_psicologo_especializacoes_psicologo_fk
        FOREIGN KEY (psicologo_id)
            REFERENCES tb_psicologo (id)
            ON DELETE CASCADE,
    CONSTRAINT tb_psicologo_especializacoes_especializacao_fk
        FOREIGN KEY (especializacao_id)
            REFERENCES tb_especializacao (id)
            ON DELETE CASCADE
);


-- ============================================================
-- IntervaloDisponibilidade
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_intervalo_disponibilidade
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_inicio TIMESTAMP(6) NOT NULL,
    data_hora_fim    TIMESTAMP(6) NOT NULL,
    psicologo_id     INTEGER      NOT NULL,
    CONSTRAINT tb_intervalo_disponibilidade_psicologo_fk
        FOREIGN KEY (psicologo_id)
            REFERENCES tb_psicologo (id)
            ON DELETE CASCADE
);

-- Índice equivalente ao MySQL: INDEX tb_intervalo_disponibilidade_psicologo_dhi_idx (psicologo_id, data_hora_inicio)
CREATE INDEX IF NOT EXISTS tb_intervalo_disponibilidade_psicologo_dhi_idx
    ON tb_intervalo_disponibilidade (psicologo_id, data_hora_inicio);


-- ============================================================
-- Consulta
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_consulta
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora_solicitada TIMESTAMP(6)   NOT NULL,
    data_hora_agendada   TIMESTAMP(6)   NOT NULL,
    duracao              BIGINT         NULL CHECK (duracao IS NULL OR duracao >= 0),
    estado               VARCHAR(20)    NOT NULL DEFAULT 'SOLICITADA',
    anotacoes            TEXT           NULL,
    checklist_tarefas    TEXT           NULL,
    paciente_id          INTEGER        NOT NULL,
    psicologo_id         INTEGER        NOT NULL,
    jitsi_room           VARCHAR(128)   NULL,
    CONSTRAINT tb_consulta_paciente_fk
        FOREIGN KEY (paciente_id)
            REFERENCES tb_paciente (id)
            ON DELETE CASCADE,
    CONSTRAINT tb_consulta_psicologo_fk
        FOREIGN KEY (psicologo_id)
            REFERENCES tb_psicologo (id)
            ON DELETE CASCADE
);

-- Índices equivalentes aos do MySQL
CREATE INDEX IF NOT EXISTS tb_consulta_estado_dh_idx
    ON tb_consulta (estado, data_hora_agendada);

CREATE INDEX IF NOT EXISTS tb_consulta_paciente_dh_idx
    ON tb_consulta (paciente_id, data_hora_agendada);

CREATE INDEX IF NOT EXISTS tb_consulta_psicologo_dh_idx
    ON tb_consulta (psicologo_id, data_hora_agendada);


-- ============================================================
-- Notificacao
-- ============================================================

CREATE TABLE IF NOT EXISTS tb_notificacao
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo             VARCHAR(50) NOT NULL,
    lida             BOOLEAN     NOT NULL DEFAULT FALSE,
    data_hora_criada TIMESTAMP(6) NOT NULL,
    remetente_id     INTEGER     NULL,
    destinatario_id  INTEGER     NOT NULL,
    consulta_id      INTEGER     NOT NULL,
    CONSTRAINT tb_notificacao_remetente_fk
        FOREIGN KEY (remetente_id)
            REFERENCES tb_usuario (id)
            ON DELETE CASCADE,
    CONSTRAINT tb_notificacao_destinatario_fk
        FOREIGN KEY (destinatario_id)
            REFERENCES tb_usuario (id)
            ON DELETE CASCADE,
    CONSTRAINT tb_notificacao_consulta_fk
        FOREIGN KEY (consulta_id)
            REFERENCES tb_consulta (id)
            ON DELETE CASCADE
);

-- Índices equivalentes
CREATE INDEX IF NOT EXISTS tb_notificacao_destinatario_lida_idx
    ON tb_notificacao (destinatario_id, lida);

CREATE INDEX IF NOT EXISTS tb_notificacao_consulta_idx
    ON tb_notificacao (consulta_id);
