# Generated by Django 5.1.7 on 2025-04-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_paciente_psicologo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Psicologo',
        ),
    ]
