# Generated by Django 5.1.7 on 2025-05-14 18:08

import terapia.utils.availability
import terapia.utils.cpf
import terapia.utils.crp
import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_marcada', models.DateTimeField(validators=[terapia.utils.validators.validate_antecedencia], verbose_name='Data e Hora Marcada')),
                ('duracao', models.IntegerField(verbose_name='Duração que a consulta teve em minutos')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADA', 'Finalizada')], default='SOLICITADA', max_length=20, verbose_name='Estado')),
                ('anotacoes', models.TextField(blank=True, null=True, verbose_name='Anotações')),
                ('checklist_tarefas', models.TextField(blank=True, null=True, verbose_name='Checklist de Tarefas')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialização',
                'verbose_name_plural': 'Especializações',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[terapia.utils.cpf.validate_cpf], verbose_name='CPF')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('crp', models.CharField(max_length=20, unique=True, validators=[terapia.utils.crp.validate_crp], verbose_name='CRP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='psicologos/fotos/', verbose_name='Foto')),
                ('sobre_mim', models.TextField(blank=True, verbose_name='Sobre Mim')),
                ('valor_consulta', models.DecimalField(blank=True, decimal_places=2, help_text='Entre R$ 20,00 e R$ 4.999,99', max_digits=10, null=True, validators=[terapia.utils.validators.validate_valor_consulta], verbose_name='Valor da Consulta')),
                ('disponibilidade', models.JSONField(blank=True, null=True, validators=[terapia.utils.availability.validate_disponibilidade], verbose_name='Disponibilidade')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
    ]
