# Generated by Django 5.1.7 on 2025-04-20 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('crp', models.CharField(max_length=20, unique=True, verbose_name='CRP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='psicologos/fotos/', verbose_name='Foto')),
                ('sobre_mim', models.TextField(blank=True, verbose_name='Sobre Mim')),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Consulta')),
                ('disponibilidade', models.JSONField(blank=True, default=dict, verbose_name='Disponibilidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
    ]
