# Generated by Django 5.1.8 on 2025-04-22 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='disponibilidade',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da Consulta'),
        ),
    ]
