# Generated by Django 5.1.8 on 2025-08-13 13:44

import django.db.models.deletion
import terapia.validadores.geral
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terapia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, validators=[terapia.validadores.geral.validate_usuario_nao_psicologo], verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.paciente'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='especializacoes',
            field=models.ManyToManyField(blank=True, related_name='psicologos', to='terapia.especializacao', verbose_name='Especializações'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL, validators=[terapia.validadores.geral.validate_usuario_nao_paciente], verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='intervalodisponibilidade',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade', to='terapia.psicologo', verbose_name='Psicólogo'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(limit_choices_to=models.Q(('valor_consulta__isnull', False), ('especializacoes__isnull', False), ('disponibilidade__isnull', False)), on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.psicologo'),
        ),
    ]
