# Generated by Django 5.1.8 on 2025-11-22 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['psicologo', 'data_hora_agendada'], name='terapia_con_psicolo_43bf85_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['paciente', 'data_hora_agendada'], name='terapia_con_pacient_157d77_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['estado', 'data_hora_agendada'], name='terapia_con_estado_bb37a2_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['data_hora_solicitada'], name='terapia_con_data_ho_2480d2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida', 'data_hora_criada'], name='terapia_not_destina_230de7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['remetente', 'data_hora_criada'], name='terapia_not_remeten_2ce8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='psicologo',
            index=models.Index(fields=['valor_consulta'], name='terapia_psi_valor_c_b03bd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='intervalodisponibilidade',
            constraint=models.UniqueConstraint(fields=('psicologo', 'data_hora_inicio', 'data_hora_fim'), name='uniq_intervalo_psicologo_inicio_fim'),
        ),
    ]
