# Generated by Django 5.1.7 on 2025-05-30 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_hora_solicitada', '-data_hora_agendada'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(limit_choices_to=models.Q(('valor_consulta__isnull', False), ('especializacoes__isnull', False), models.Q(('disponibilidade__exact', []), _negated=True)), on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.psicologo'),
        ),
    ]
