# Generated by Django 5.1.7 on 2025-06-03 21:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='data_hora_fim',
            field=models.DateTimeField(help_text='A data deste campo é apenas utilizada para obter o dia da semana do intervalo, o que significa que a data em si não importa desde que o dia da semana esteja correto. Por conveniência, usa-se a semana de 01/jan/0007 até 07/jan/0007, isto é, datetime(7, 1, 1) até datetime(7, 1, 7). A razão para isso é que nessa semana, o número do dia do mês é o mesmo do dia da semana no formato ISO, ou seja: 01/jan/0007 é segunda (1), 02/jan/0007 é terça (2) ... 07/jan/0007 é domingo (7).', validators=[django.core.validators.MinValueValidator(datetime.datetime(7, 1, 1, 3, 6, 28, tzinfo=datetime.timezone.utc), message='A data deve estar entre 01/jan/0007 e 07/jan/0007.'), django.core.validators.MaxValueValidator(datetime.datetime(7, 1, 8, 3, 6, 27, tzinfo=datetime.timezone.utc), message='A data deve estar entre 01/jan/0007 e 07/jan/0007.')], verbose_name='Dia da semana e hora do fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='data_hora_inicio',
            field=models.DateTimeField(help_text='A data deste campo é apenas utilizada para obter o dia da semana do intervalo, o que significa que a data em si não importa desde que o dia da semana esteja correto. Por conveniência, usa-se a semana de 01/jan/0007 até 07/jan/0007, isto é, datetime(7, 1, 1) até datetime(7, 1, 7). A razão para isso é que nessa semana, o número do dia do mês é o mesmo do dia da semana no formato ISO, ou seja: 01/jan/0007 é segunda (1), 02/jan/0007 é terça (2) ... 07/jan/0007 é domingo (7).', validators=[django.core.validators.MinValueValidator(datetime.datetime(7, 1, 1, 3, 6, 28, tzinfo=datetime.timezone.utc), message='A data deve estar entre 01/jan/0007 e 07/jan/0007.'), django.core.validators.MaxValueValidator(datetime.datetime(7, 1, 8, 3, 6, 27, tzinfo=datetime.timezone.utc), message='A data deve estar entre 01/jan/0007 e 07/jan/0007.')], verbose_name='Dia da semana e hora do início do intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='psicologo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='disp', to='terapia.psicologo', verbose_name='Psicólogo'),
            preserve_default=False,
        ),
    ]
