# Generated by Django 5.1.8 on 2025-11-23 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_como_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_como_remetente', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('CONSULTA_SOLICITADA', 'Consulta Solicitada'), ('CONSULTA_CONFIRMADA', 'Consulta Confirmada'), ('CONSULTA_CANCELADA', 'Consulta Cancelada'), ('CONSULTA_RECUSADA', 'Consulta Recusada'), ('CONSULTA_EM_ANDAMENTO', 'Consulta Em Andamento'), ('CONSULTA_EXPIRADA', 'Consulta Expirada')], max_length=50, verbose_name='Tipo'),
        ),
    ]
