# Generated by Django 5.1.8 on 2025-04-22 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_alter_psicologo_disponibilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_marcada', models.DateTimeField(verbose_name='Data e Hora Marcada')),
                ('duracao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração (minutos)')),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADA', 'Finalizada')], default='SOLICITADA', max_length=20, verbose_name='Estado')),
                ('anotacoes', models.TextField(blank=True, verbose_name='Anotações')),
                ('checklist_tarefas', models.TextField(blank=True, verbose_name='Checklist de Tarefas')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialização',
                'verbose_name_plural': 'Especializações',
            },
        ),
    ]
