# Generated by Django 5.1.7 on 2025-05-14 20:18

import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='checklist_tarefas',
            field=models.TextField(blank=True, null=True, verbose_name='Checklist de tarefas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_hora_marcada',
            field=models.DateTimeField(validators=[terapia.utils.validators.validate_uma_hora_antecedencia], verbose_name='Data e hora para as quais a consulta foi marcada'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='duracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração que a consulta teve em minutos'),
        ),
    ]
