# Generated by Django 5.1.8 on 2025-11-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0003_alter_notificacao_destinatario_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['estado', 'data_hora_agendada'], name='consulta_estado_dh_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['paciente', 'data_hora_agendada'], name='consulta_paciente_dh_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['psicologo', 'data_hora_agendada'], name='consulta_psicologo_dh_idx'),
        ),
    ]
