# Generated by Django 5.1.8 on 2025-05-21 13:31

import django.db.models.deletion
import terapia.utils.availability
import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0003_alter_consulta_checklist_tarefas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_hora_marcada'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_hora_marcada',
            field=models.DateTimeField(validators=[terapia.utils.validators.validate_uma_hora_antecedencia], verbose_name='Data e hora marcadas para a consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.psicologo', verbose_name='Psicólogo'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='disponibilidade',
            field=models.JSONField(blank=True, default=list, validators=[terapia.utils.availability.validate_disponibilidade], verbose_name='Disponibilidade'),
        ),
    ]
