# Generated by Django 5.1.7 on 2025-06-01 23:53

import terapia.utils.availability
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0003_alter_consulta_options_alter_consulta_psicologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervaloDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana_inicio', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana do início do intervalo')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início do intervalo')),
                ('dia_semana_fim', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana do fim do intervalo')),
                ('horario_fim', models.TimeField(verbose_name='Horário de fim do intervalo')),
            ],
            options={
                'verbose_name': 'Intervalo de Disponibilidade',
                'verbose_name_plural': 'Intervalos de Disponibilidade',
            },
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='disponibilidade',
            field=models.JSONField(default=list, validators=[terapia.utils.availability.validate_disponibilidade], verbose_name='Disponibilidade'),
        ),
    ]
