# Generated by Django 5.1.7 on 2025-04-23 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0003_consulta_especializacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.psicologo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especializacao',
            name='psicologos',
            field=models.ManyToManyField(blank=True, related_name='especializacoes', to='terapia.psicologo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='duracao',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duração (minutos)'),
        ),
    ]
