# Generated by Django 5.1.8 on 2025-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0003_alter_consulta_data_hora_agendada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='duracao',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração que a consulta teve em minutos'),
        ),
    ]
