# Generated by Django 5.1.8 on 2025-09-27 17:43

import terapia.validadores.geral
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_alter_consulta_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='data_hora_fim',
            field=models.DateTimeField(help_text='A data deste campo é apenas utilizada para obter o dia da semana do intervalo, o que significa que a data em si não importa desde que o dia da semana esteja correto. Por conveniência, usa-se a semana de 01/07/2024 até 07/07/2024, isto é, datetime(2024, 7, 1, 0, 0) até datetime(2024, 7, 7, 23, 59). A razão para isso é que nessa semana, o número do dia do mês é o mesmo do dia da semana no formato ISO, ou seja: 01/07/2024 é segunda (1), 02/07/2024 é terça (2) ... e 07/07/2024 é domingo (7).', validators=[terapia.validadores.geral.validate_intervalo_disponibilidade_data_hora_range, terapia.validadores.geral.validate_divisivel_por_duracao_consulta], verbose_name='Dia da semana e hora do fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='data_hora_inicio',
            field=models.DateTimeField(help_text='A data deste campo é apenas utilizada para obter o dia da semana do intervalo, o que significa que a data em si não importa desde que o dia da semana esteja correto. Por conveniência, usa-se a semana de 01/07/2024 até 07/07/2024, isto é, datetime(2024, 7, 1, 0, 0) até datetime(2024, 7, 7, 23, 59). A razão para isso é que nessa semana, o número do dia do mês é o mesmo do dia da semana no formato ISO, ou seja: 01/07/2024 é segunda (1), 02/07/2024 é terça (2) ... e 07/07/2024 é domingo (7).', validators=[terapia.validadores.geral.validate_intervalo_disponibilidade_data_hora_range, terapia.validadores.geral.validate_divisivel_por_duracao_consulta], verbose_name='Dia da semana e hora do início do intervalo'),
        ),
    ]
