# Generated by Django 5.1.7 on 2025-05-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.psicologo'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='sobre_mim',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre Mim'),
        ),
    ]
