# Generated by Django 5.1.7 on 2025-06-02 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_intervalodisponibilidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalodisponibilidade',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disp', to='terapia.psicologo', verbose_name='Psicólogo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[(None, 'Estado'), ('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADA', 'Finalizada')], default='SOLICITADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='dia_semana_fim',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Dia da Semana'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana do fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='dia_semana_inicio',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Dia da Semana'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana do início do intervalo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
