# Generated by Django 5.2.8 on 2025-11-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_consulta_consulta_estado_dh_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervaloDisponibilidadeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana_inicio_iso', models.IntegerField(help_text='1=Segunda, 2=Terça, ..., 7=Domingo (formato ISO)', verbose_name='Dia da semana de início')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('dia_semana_fim_iso', models.IntegerField(help_text='1=Segunda, 2=Terça, ..., 7=Domingo (formato ISO)', verbose_name='Dia da semana de fim')),
                ('hora_fim', models.TimeField(verbose_name='Hora de fim')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade_template', to='terapia.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Template de Disponibilidade',
                'verbose_name_plural': 'Templates de Disponibilidade',
                'ordering': ['dia_semana_inicio_iso', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='IntervaloDisponibilidadeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(db_index=True, help_text='Sempre armazenar a segunda-feira da semana (isoweekday=1)', verbose_name='Segunda-feira da semana')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data e hora de início')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Data e hora de fim')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidade_overrides', to='terapia.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Override de Disponibilidade',
                'verbose_name_plural': 'Overrides de Disponibilidade',
                'ordering': ['semana_inicio', 'data_hora_inicio'],
                'indexes': [models.Index(fields=['psicologo', 'semana_inicio'], name='terapia_int_psicolo_cc0345_idx'), models.Index(fields=['data_hora_inicio', 'data_hora_fim'], name='terapia_int_data_ho_e9eb11_idx')],
                'unique_together': {('psicologo', 'semana_inicio', 'data_hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='SemanaDisponibilidadeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(db_index=True, help_text='Sempre armazenar a segunda-feira da semana (isoweekday=1)', verbose_name='Segunda-feira da semana')),
                ('comportamento', models.CharField(choices=[('TEMPLATE', 'Usar template padrão'), ('CUSTOM', 'Horários customizados (ignorar template)'), ('UNAVAILABLE', 'Indisponível (sem atendimentos)')], default='TEMPLATE', max_length=20, verbose_name='Comportamento')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_semanas', to='terapia.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Configuração de Semana',
                'verbose_name_plural': 'Configurações de Semanas',
                'ordering': ['semana_inicio'],
                'unique_together': {('psicologo', 'semana_inicio')},
            },
        ),
    ]
