# Generated by Django 5.2.8 on 2025-12-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_consulta_consulta_estado_dh_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('terapia', 'Consulta').objects.update(checklist_tarefas=None),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='checklist_tarefas',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Checklist de tarefas'),
        ),
    ]
