# Generated by Django 5.1.7 on 2025-04-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_consulta_paciente_consulta_psicologo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especializacao',
            name='psicologos',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='especializacoes',
            field=models.ManyToManyField(blank=True, related_name='psicologos', to='terapia.especializacao'),
        ),
    ]
