# Generated by Django 5.1.8 on 2025-05-28 11:46

import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_alter_consulta_psicologo_alter_psicologo_sobre_mim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_hora_marcada',
            field=models.DateTimeField(validators=[terapia.utils.validators.validate_data_hora_marcada], verbose_name='Data e hora marcadas para a consulta'),
        ),
    ]
