# Generated by Django 5.1.7 on 2025-06-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_pleasefunction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasefunction',
            name='data_hora_fim',
            field=models.DateTimeField(verbose_name='Dia da semana e hora do fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='pleasefunction',
            name='data_hora_inicio',
            field=models.DateTimeField(verbose_name='Dia da semana e hora do início do intervalo'),
        ),
    ]
