# Generated by Django 5.1.7 on 2025-06-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_intervalodisponibilidade_psicologo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='dia_semana_fim',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Dia da semana'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana do fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='dia_semana_inicio',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Dia da semana'), (0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana do início do intervalo'),
        ),
    ]
