# Generated by Django 5.2.8 on 2025-12-02 18:53

import django.db.models.deletion
import terapia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_alter_consulta_checklist_tarefas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data_hora_agendada'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveIndex(
            model_name='consulta',
            name='consulta_estado_dh_idx',
        ),
        migrations.RemoveIndex(
            model_name='consulta',
            name='consulta_paciente_dh_idx',
        ),
        migrations.RemoveIndex(
            model_name='consulta',
            name='consulta_psicologo_dh_idx',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Sala Jitsi'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='terapia.psicologo', validators=[terapia.models.validate_psicologo_completo], verbose_name='Psicólogo'),
        ),
    ]
