# Generated by Django 5.1.8 on 2025-09-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_alter_intervalodisponibilidade_data_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('psicologo', 'data_hora_agendada'), name='uniq_psicologo_horario_consulta_ativa'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('paciente', 'data_hora_agendada'), name='uniq_paciente_horario_consulta_ativa'),
        ),
    ]
