# Generated by Django 5.1.8 on 2025-04-24 20:14

import django.core.validators
import terapia.utils.availability
import terapia.utils.cpf
import terapia.utils.crp
import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_remove_especializacao_psicologos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_hora_marcada',
            field=models.DateTimeField(validators=[terapia.utils.validators.validate_future_datetime], verbose_name='Data e Hora Marcada'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='duracao',
            field=models.IntegerField(validators=[terapia.utils.validators.validate_duracao_range], verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADA', 'Finalizada')], default='SOLICITADA', max_length=20, validators=[terapia.utils.validators.validate_estado_solicitada], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[terapia.utils.cpf.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='crp',
            field=models.CharField(max_length=20, unique=True, validators=[terapia.utils.crp.validate_crp], verbose_name='CRP'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='disponibilidade',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[terapia.utils.availability.validate_disponibilidade], verbose_name='Disponibilidade'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entre R$ 20,00 e R$ 4 999,99', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), terapia.utils.validators.validate_valor_consulta], verbose_name='Valor da Consulta'),
        ),
    ]
