# Generated by Django 5.1.8 on 2025-10-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0006_consulta_uniq_psicologo_horario_consulta_ativa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consulta',
            name='uniq_psicologo_horario_consulta_ativa',
        ),
        migrations.RemoveConstraint(
            model_name='consulta',
            name='uniq_paciente_horario_consulta_ativa',
        ),
    ]
