# Generated by Django 5.1.7 on 2025-06-04 21:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0006_alter_pleasefunction_data_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasefunction',
            name='data_hora_inicio',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(7, 1, 1, 3, 6, 28, tzinfo=datetime.timezone.utc), message='A data deve estar entre 01/01/0007 e 08/01/0007.'), django.core.validators.MaxValueValidator(datetime.datetime(8, 1, 7, 3, 6, 28, tzinfo=datetime.timezone.utc), message='A data deve estar entre 01/01/0007 e 08/01/0007.')], verbose_name='Dia da semana e hora do início do intervalo'),
        ),
    ]
