# Generated by Django 5.1.7 on 2025-06-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0007_alter_pleasefunction_data_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasefunction',
            name='data_hora_inicio',
            field=models.DateTimeField(verbose_name='Dia da semana e hora do início do intervalo'),
        ),
    ]
