# Generated by Django 5.1.7 on 2025-04-29 01:30

import django.core.validators
import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0007_alter_consulta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entre R$ 20,00 e R$ 4.999,99', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), terapia.utils.validators.validate_valor_consulta], verbose_name='Valor da Consulta'),
        ),
    ]
