# Generated by Django 4.0.1 on 2025-10-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0007_remove_consulta_uniq_psicologo_horario_consulta_ativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='especializacoes',
            field=models.ManyToManyField(blank=True, related_name='psicologos', to='terapia.Especializacao', verbose_name='Especializações'),
        ),
    ]
