# Generated by Django 5.1.8 on 2025-10-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0008_alter_psicologo_especializacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalodisponibilidade',
            name='semana',
            field=models.DateField(blank=True, null=True, verbose_name='Início da semana (segunda-feira)'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='disponibilidade_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='Overrides semanais de disponibilidade'),
        ),
    ]
