# Generated by Django 5.1.8 on 2025-11-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0008_alter_psicologo_especializacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='jitsi_room',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sala Jitsi'),
        ),
    ]
