# Generated by Django 5.1.8 on 2025-11-21 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0008_alter_psicologo_especializacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTA_SOLICITADA', 'Consulta Solicitada'), ('CONSULTA_ACEITA', 'Consulta Aceita'), ('CONSULTA_CANCELADA', 'Consulta Cancelada')], max_length=50, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_hora_criada', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='terapia.consulta', verbose_name='Consulta')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_como_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Psicólogo')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_como_remetente', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_hora_criada'],
            },
        ),
    ]
