# Generated by Django 5.1.7 on 2025-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0008_alter_pleasefunction_data_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModelTrustMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Dia da semana e hora do início do intervalo')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Dia da semana e hora do fim do intervalo')),
            ],
        ),
        migrations.DeleteModel(
            name='PleaseFunction',
        ),
    ]
