# Generated by Django 5.1.7 on 2025-05-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0009_alter_paciente_foto_alter_psicologo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='foto_de_perfil.jpg', upload_to='pacientes/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='foto',
            field=models.ImageField(default='foto_de_perfil.jpg', upload_to='psicologos/fotos/', verbose_name='Foto'),
        ),
    ]
