# Generated by Django 5.1.8 on 2025-10-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0009_intervalodisponibilidade_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalodisponibilidade',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='disponibilidade_overrides',
        ),
        migrations.CreateModel(
            name='WeekAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='Segunda-feira da semana (local)')),
                ('kind', models.CharField(choices=[('ANCHOR', 'Anchor (replica adiante)'), ('OVERRIDE', 'Override (só esta semana)')], max_length=8)),
                ('matriz', models.JSONField(verbose_name='Matriz 7xN de booleanos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_avails', to='terapia.psicologo')),
            ],
            options={
                'ordering': ['-week_start', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'OVERRIDE')), fields=('psicologo', 'week_start'), name='uniq_override_por_semana_por_psicologo'), models.UniqueConstraint(condition=models.Q(('kind', 'ANCHOR')), fields=('psicologo', 'week_start'), name='uniq_anchor_por_semana_por_psicologo')],
            },
        ),
    ]
