# Generated by Django 5.1.8 on 2025-10-03 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0010_remove_intervalodisponibilidade_semana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekavailability',
            options={'ordering': ['week_start']},
        ),
        migrations.RemoveConstraint(
            model_name='weekavailability',
            name='uniq_override_por_semana_por_psicologo',
        ),
        migrations.RemoveConstraint(
            model_name='weekavailability',
            name='uniq_anchor_por_semana_por_psicologo',
        ),
        migrations.AddField(
            model_name='weekavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weekavailability',
            name='kind',
            field=models.CharField(choices=[('OVERRIDE', 'Override'), ('ANCHOR', 'Anchor')], max_length=16),
        ),
        migrations.AlterField(
            model_name='weekavailability',
            name='matriz',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='weekavailability',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_availability', to='terapia.psicologo'),
        ),
        migrations.AlterField(
            model_name='weekavailability',
            name='week_start',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='weekavailability',
            index=models.Index(fields=['psicologo', 'week_start'], name='terapia_wee_psicolo_021786_idx'),
        ),
        migrations.AddIndex(
            model_name='weekavailability',
            index=models.Index(fields=['psicologo', 'kind', 'week_start'], name='terapia_wee_psicolo_55973a_idx'),
        ),
        migrations.AddConstraint(
            model_name='weekavailability',
            constraint=models.UniqueConstraint(fields=('psicologo', 'week_start'), name='uniq_psicologo_weekstart'),
        ),
    ]
