# Generated by Django 5.1.7 on 2025-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0011_alter_paciente_foto_alter_psicologo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='especializacoes',
            field=models.ManyToManyField(blank=True, related_name='psicologos', to='terapia.especializacao', verbose_name='Especializações'),
        ),
    ]
