# Generated by Django 5.1.7 on 2025-05-11 12:08

import terapia.utils.availability
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0012_alter_psicologo_especializacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='disponibilidade',
            field=models.JSONField(blank=True, null=True, validators=[terapia.utils.availability.validate_disponibilidade], verbose_name='Disponibilidade'),
        ),
    ]
