# Generated by Django 5.1.7 on 2025-06-04 21:49

import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0013_fake_delete_anothermodeltrustme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fake',
            name='data_hora_inicio',
            field=models.DateTimeField(validators=[terapia.utils.validators.validate_intervalo_disponibilidade_datetime_range], verbose_name='Dia da semana e hora do início do intervalo'),
        ),
    ]
