# Generated by Django 5.1.7 on 2025-06-04 22:22

import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0014_alter_fake_data_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pwease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(validators=[terapia.utils.validators.validate_intervalo_disponibilidade_datetime_range], verbose_name='Dia da semana e hora do início do intervalo')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Dia da semana e hora do fim do intervalo')),
            ],
        ),
        migrations.DeleteModel(
            name='Fake',
        ),
    ]
