# Generated by Django 5.1.7 on 2025-06-04 22:32

import terapia.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0016_agoravai_delete_pwease_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgoraVai',
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='data_hora_fim',
            field=models.DateTimeField(help_text='A data deste campo é apenas utilizada para obter o dia da semana do intervalo, o que significa que a data em si não importa desde que o dia da semana esteja correto. Por conveniência, usa-se a semana de 01/07/2024 até 08/07/2024, isto é, datetime(2024, 7, 1, 0, 0) até datetime(2024, 7, 8, 0, 0). A razão para isso é que nessa semana, o número do dia do mês é o mesmo do dia da semana no formato ISO, ou seja: 01/07/2024 é segunda (1), 02/07/2024 é terça (2) ... 07/07/2024 é domingo (7), e 08/07/2024 é segunda (1) novamente.', validators=[terapia.utils.validators.validate_intervalo_disponibilidade_datetime_range], verbose_name='Dia da semana e hora do fim do intervalo'),
        ),
        migrations.AlterField(
            model_name='intervalodisponibilidade',
            name='data_hora_inicio',
            field=models.DateTimeField(help_text='A data deste campo é apenas utilizada para obter o dia da semana do intervalo, o que significa que a data em si não importa desde que o dia da semana esteja correto. Por conveniência, usa-se a semana de 01/07/2024 até 08/07/2024, isto é, datetime(2024, 7, 1, 0, 0) até datetime(2024, 7, 8, 0, 0). A razão para isso é que nessa semana, o número do dia do mês é o mesmo do dia da semana no formato ISO, ou seja: 01/07/2024 é segunda (1), 02/07/2024 é terça (2) ... 07/07/2024 é domingo (7), e 08/07/2024 é segunda (1) novamente.', validators=[terapia.utils.validators.validate_intervalo_disponibilidade_datetime_range], verbose_name='Dia da semana e hora do início do intervalo'),
        ),
    ]
